FROM redis:7-alpine@sha256:858f009f9709ce576febc734aa78b8f6d624b82571f9ddb6bda4377c833b3499

RUN task_redis_sha256="$(sha256sum /usr/local/bin/redis-server)" \
    && apk add --no-cache --upgrade 'libcrypto3>=3.3.7-r2' 'libssl3>=3.3.7-r2' \
    && test "$task_redis_sha256" = "$(sha256sum /usr/local/bin/redis-server)" \
    && apk info -v libcrypto3 libssl3 \
    && redis-server --version
